spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:shop_user}
    password: ${SPRING_DATASOURCE_PASSWORD:shop_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
